### ISSUE TITLE
Avoid docker login issue with X11

### ISSUE THREAD

**Issue by coute** [nickjj/ansible-docker#104] opened 2021-01-22 16:21 UTC
Hello @nickjj,
I encountered an issue with the docker login command after i have installed docker with your role.
I got the message :
```Error saving credentials: error storing credentials - err: exit status 1, out: `Cannot autolaunch D-Bus without X11 $DISPLAY` ``` 
According to this post : https://github.com/docker/compose/issues/6023#issuecomment-419792269 the fix consist into installing the "pass" package.
I tried it and it worked.
You should envisage to add this package in default docker__package_dependencies list to avoid this issue.

**Comment by nickjj** [comment] 2021-01-22 16:33
Hi,

Which OS / distro is this affecting?

**Comment by coute** [comment] 2021-01-22 16:49
The issue was with Debian buster.
I installed docker and docker compose with the role only.

**Comment by coute** [comment] 2021-01-22 16:59
I had an other problem with registries.
I used the docker__registries variable to set a private registry and the roles is set with become: yes.
The docker-login task worked, but redentials are stored in .docker folder that is only root accessible.
`~$ ls -l -a                                                                                                                                                                                                                     total 40                                                                                                                                                                                                                                     drwxr-xr-x 6 ansible ansible 4096 Jan 22 17:36 .                                                                                                                                                                                             drwxr-xr-x 5 root    root    4096 Jan 22 15:11 ..                                                                                                                                                                                            -rw------- 1 ansible ansible  672 Jan 22 17:23 .bash_history                                                                                                                                                                                 -rw-r--r-- 1 ansible ansible  220 Apr 18  2019 .bash_logout                                                                                                                                                                                  -rw-r--r-- 1 ansible ansible 3526 Apr 18  2019 .bashrc                                                                                                                                                                                       drwxr-xr-x 2 root    root    4096 Jan 22 17:36 .docker                                                                                                                                                                                       drwx------ 3 ansible ansible 4096 Jan 22 15:18 .gnupg                                                                                                                                                                                        -rw-r--r-- 1 ansible ansible  807 Apr 18  2019 .profile                                                                                                                                                                                      drwx------ 2 ansible ansible 4096 Jan 22 15:11 .ssh                                                                                                                                                                                          drwx------ 3 ansible ansible 4096 Jan 22 17:36 tmp`

So the docker login command  doesn't work after the installation with the ansible user.

**Comment by coute** [comment] 2021-01-22 17:23
> 
> 
> I had an other problem with registries.
> I used the docker__registries variable to set a private registry.
> The roles is set with `become: yes`
> 
> I launched the playbook and the docker-login task worked. But docker credentials that is stored in .docker folder is only root accessible.
> 
> ```
> ls -lha /home/ansible/.docker/
> total 12K
> drwxr-xr-x 2 root    root    4.0K Jan 22 17:36 .
> drwxr-xr-x 6 ansible ansible 4.0K Jan 22 17:36 ..
> -rw------- 1 root    root     142 Jan 22 17:36 config.json
> ```
> 
> So the docker login command doesn't work after the installation with the ansible user.

I used ```become_flags: "-i"``` in playbook to fix the issue.
The .docker folder has been created in root home folder.

**Comment by nickjj** [comment] 2021-01-22 17:27
Which Buster ISO are you using, or cloud hosting provider if you can't pick it?

**Comment by coute** [comment] 2021-01-22 17:27
AWS buster ISO

**Comment by nickjj** [comment] 2021-01-22 17:29
Can you link me to the exact AMI you're using?

**Comment by coute** [comment] 2021-01-22 17:46
https://aws.amazon.com/marketplace/pp/B0859NK4HC?ref=cns_srchrow

**Comment by nickjj** [comment] 2021-01-22 18:21
The X11 issue seems related to that specific ISO of Debian. I can't reproduce it on a few other cloud vendor's versions of Debian or what comes with Vagrant's Debian box or Docker's variant of Debian.

**Comment by coute** [comment] 2021-01-22 18:52
I have made some tests on a Vagrant host with a buster image.
I found that a previous role in my  playbook install python3-docker package with apt.
This package depends on golang-docker-credential-helpers
If I remove both of them, that fix the issue.
My bad.

**Comment by nickjj** [comment] 2021-01-22 19:00
Ok, so it sounds like the X11 issue is resolved.

Going to close this.

The file permission issue with the login credentials is a separate issue and I'm working on a patch for that.

**Closed by nickjj** 2021-01-22 19:00 UTC
